######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 23 12:09:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FindDialog.h
SOURCES += FindDialog.cpp main.cpp
